### ISSUE TITLE
Status/Info logging

### ISSUE THREAD

**Issue by bakerkj** [stripydog/kplex#10]
Keith,

Is there a chance to add a bit more "status" logging (at either the info or debugging level)?

Some that I can think would be useful

1) Logging successful startup of the daemon
2) Logging the successful opening of an input/output file
3) Logging successful TCP connections (client and server mode)
4) Logging listening on a UDP port 

I'm sure there are others...

-- Ken

**Comment by stripydog** [comment]
Yes.  There's already a bit more in the current develop branch than was in
1.3.1.  I'll have a look at what you'v suggested tomorrow.

**Comment by bakerkj** [comment]
thanks!

**Comment by stripydog** [comment]
There is now *lots* more debugging in the develop branch.  I'll probably add more later as needed but will this do for the next release?  Let me know.

**Comment by bakerkj** [comment]
I am running 1.3.2 with -d 3 and I'll let you know how it goes.

**Comment by bakerkj** [comment]
The additional logging is helpful.  Thanks!

**Comment by stripydog** [comment]
OK.  Still to do: add more debugging and internationalise it but closing this now
