### ISSUE TITLE
segmentation fault on "garbage" input

### ISSUE THREAD

**Issue by doccodyblue** [stripydog/kplex#13]
hi!

I have kplex 1.3.4 running on Raspbian. Besides a lot of hardware, there is one of the serial ports RX connected to 2 TX lines (Windmeter and Dephtsounder). I know, this violates the NMEA0183 specs, but works in general. Downside: Sometimes both devices transmit simultaneously and a "garbage" packet is received. If one of these packets come in to kplex via /dev/ttyS0, this forces a "segmentation fault". No further info is given, even on debug level 9. I reproduced that a couple of times. 

I made a dump of the received packets on gdrive
[https://drive.google.com/open?id=0BzKlfX0_ZkUfNnJXc1RhUmZwQnM](url)

Unfortunately I couldn´t get kplex to segfault by simply feeding the file into a pty

Would be nice if we could make that "bomb proof" since "garbage" could occur at on a serial line in general.

Andy

**Comment by stripydog** [comment]
>
> Would be nice if we could make that "bomb proof" since "garbage" could
> occur at on a serial line in general.
>
>
Thanks.  I'll take a look at this later this week.  kplex *should* be
bullet proof in this respect and if it's segfaulting that's *definitely* a
bug.

**Comment by stripydog** [comment]
I don't seem to be able to access the file you've linked to. Any chance you could attach it instead?

**Comment by doccodyblue** [comment]
Here we go. Let me know if I can assist somehow. 

[WIND.zip](https://github.com/stripydog/kplex/files/356609/WIND.zip)

**Comment by stripydog** [comment]
Will do. Might not get a chance to check this out for a few days but hope to make some time later in the week

**Comment by doccodyblue** [comment]
great. I am also able to reproduce the segfault at home now, not only at the boat. Connected /dev/ttyUSB1 and /dev/ttyS0 with a crossover-line. Kplex runs just fine until I feed the attached data to the (in fact any) serial port. Looks like that:
root@vegas-nmea:~# kplex -d 9 -f /etc/kplex.conf
kplex DEBUG: Using config file /etc/kplex.conf
kplex DEBUG: kplex starting, config file /etc/kplex.conf
kplex DEBUG: tty-dAISy: opened serial device /dev/ttyACM0 for input
kplex DEBUG: usb-ShipBus: opened serial device /dev/ttyUSB1 for input
kplex DEBUG: gpsd: initialised
kplex DEBUG: tcp-110: initialised
kplex DEBUG: tcp-111: initialised
kplex DEBUG: nmea-local-in: created pty link /tmp/nmea.in.tty to /dev/pts/4
kplex DEBUG: nmea-local-out: created pty link /tmp/nmea.out.tty to /dev/pts/5
kplex DEBUG: nmea-local-inject: created pty link /tmp/nmea.inject.tty to /dev/pts/6
Segmentation fault
root@vegas-nmea:~#

**Comment by stripydog** [comment]
I'm not having a lot of luck reproducing this although I'm currently not near any serial adapters and trying to do it all with ptys.  Can you compile from source? If so, do so (grab the 1.3.4 source from the kplex web site).  Don't override CFLAGS (keep -g) and make sure you have core dumps enabled  When you get a core dump either compress it and post it (if small enough) or let me know if that doesn't work and we we can get a stack trace at least

**Comment by doccodyblue** [comment]
Here we go. I set up a new Raspberry, since the other one is on the boat now. Kplex was compiled from the sourced. A Windows PC is hooked up to the Rasp via a serial-usb adaptor. If the file "WIND.log" is uploaded to the /dev/ttyS0, segfault occurs. I hope, the core dump is ok, since I have only a little experience with C. Let me know, if I can do anything else. Will keep the setup here though. 

[core-dump-kplex-ttyS0.zip](https://github.com/stripydog/kplex/files/365329/core-dump-kplex-ttyS0.zip)

**Comment by stripydog** [comment]
It looks fine. Just need to get back to the boat and dig up a pi.  Really appreciate your help with this

**Comment by stripydog** [comment]
Just to let you know I haven't forgotten about this: things have just been a bit hectic (sorry).  Having trouble with the core file which might be due to the combination of slightly architectural variations between the versions of pi and OSes were using and my lack of competence in dealing with that.  What kind of pi are you using?  I've brought my pi3 with recent raspbian with me this week to replace the pi1 with an older raspbian which I was using before.  If you *do* get a chance could you try the following?
gdb <path to the kplex you were using compiled with -g> <path to core file>

...then get a backtrack with:
bt
and post?  Meantime I'll try and rig up the other pi

**Comment by stripydog** [comment]
ok the problem I was having is an armv6 vs armv7 thing. Now have the pi3 up and running and the crash was due to a lack of bounds checking in the checksum checking (so don't bother with the backtrace etc.).  Of course now I have to figure out why it was even checking the checsum...

**Comment by stripydog** [comment]
Andy are you the same Andrew who was posting an issue with data from combined instruments being dropped?  I was assuming you were and assuming the config file was what you posted but here's the thing: the crash happened because of a lack of bounds checking in the checksum routine. Stupid error on my part. Easy fix.  But why was it even doing the checksumming?  Because it inherited "checksum=yes" from a global setting of checksum=yes.  If that wasn't present in your config file (please confirm) then I need to figure out where it came from.

Thanks for raising this.  Also thanks for making me compile from source: I see a makefile issue I recently introduced as well

**Comment by stripydog** [comment]
Fix pushed to git develop branch (though need to work on Makefile later)

**Comment by doccodyblue** [comment]
Great news. Confirmed about "checksum=yes", I have it in kplex.conf.
I would get the source and try it out right away, but my Pi refuses to talk to the serial port now. Maybe its the max3232 or the pi3 timing issue with the internal UART. Have to fix that first, whene I am back home. Just cruising the baltic sea .) Keep up the great work and thanks for your help!! Andy

**Comment by doccodyblue** [comment]
Found the time to hook up a fallback USB dongle to NMEA. Fix confirmed!
Thx, Andy

**Comment by stripydog** [comment]
Thanks for your feedback in fixing this!

**Comment by doccodyblue** [comment]
I am afraid a got segfaul again. I will come back with more details. It still only occurs with checksum=yes

Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: stripydog <notifications@github.com> Datum: 27.07.16  23:05  (GMT+01:00) An: stripydog/kplex <kplex@noreply.github.com> Cc: doccodyblue <doccodyblue@gmail.com>, State change <state_change@noreply.github.com> Betreff: Re: [stripydog/kplex] segmentation fault on "garbage" input (#13) 
Thanks for your feedback in fixing this!

**Comment by stripydog** [comment]
So sorry to have wasted your time.  If you could  post another crash dump that will help although I should look more carefully at the code: last fix seemed obvious and I didn't clearly didn't check it enough

**Comment by stripydog** [comment]
OK I've worked out where there could be a problem.  Let me fix that this evening and let you try it before you go to any more trouble

**Comment by stripydog** [comment]
I've pushed a better fix to github.  Your choice whether to try it now or wait until tomorrow when I've had a chance to think about whether it has any obvious mistakes like the last one :-).  I *think* this is OK...

**Comment by doccodyblue** [comment]
Not sure if that's possible, but with the development branch version kplex doesn't let GPS packets from gpsd through to my ttys.No matter if checksum yes or no. Back to the old executable, streams flowing. Didn't have time to look deeper into it yet :)
Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: stripydog <notifications@github.com> Datum: 28.07.16  13:39  (GMT+01:00) An: stripydog/kplex <kplex@noreply.github.com> Cc: doccodyblue <doccodyblue@gmail.com>, State change <state_change@noreply.github.com> Betreff: Re: [stripydog/kplex] segmentation fault on "garbage" input (#13) 
I've pushed a better fix to github.  Your choice whether to try it now or wait until tomorrow when I've had a chance to think about whether it has any obvious mistakes like the last one :-).  I think this is OK...

**Comment by stripydog** [comment]
*sigh* that's because I'm not cut out for doing a proper job and end up dashing off unchecked fixes in a hurry.  Try the new one I just pushed to github.....

**Comment by doccodyblue** [comment]
Hate to tell you, but now

1. kplex seem to run stable
2. kplex seem to filter out wrong checksum

but

3. kplex doesn´t loopback on my seril interface anymore :D thats where my
nmea repeater display is hooked up. I can reproduce this issue by switching
between the dev branch and the master branch

This is the config part for the serial:

[serial]
name=tty-Wind_MD150
filename=/dev/ttyUSB0
baud=4800
direction=both
optional=yes
loopback=yes
#ofilter=-AI***:-GP***:+all
ofilter=-AI***:-GPGSA:-GPGSV:-CCADS:+all

But still: Good job on that piece of software. Cant live without it :)

Andy



2016-07-28 20:08 GMT+02:00 stripydog <notifications@github.com>:

**Comment by stripydog** [comment]
I diffed what I've done in develop vs master and all that seems to have changed is the checksumming. The changes to the isprop macro should be irrelevant and were just a cure for a potential crash with very short sentences. If you have two source trees there can you confirm that that's and some minor things in the makefile are all that differs for you?  I'm assuming you're using the same config file, sources etc.  Is global checksumming switched on or off?  And it isn't anything that's being caught by your ofilter that's looping back is it?

**Comment by doccodyblue** [comment]
Aaarrr so sorry, my fault. System messed up the USB configuration and the USB interfaced where mixed up :( shouldn't happen. So far the development branch does what it should!!
Thanks!!Andy

-------- Ursprüngliche Nachricht --------Von: stripydog <notifications@github.com> Datum: 03.08.16  22:58  (GMT+01:00) An: stripydog/kplex <kplex@noreply.github.com> Cc: doccodyblue <doccodyblue@gmail.com>, State change <state_change@noreply.github.com> Betreff: Re: [stripydog/kplex] segmentation fault on "garbage" input (#13) 
I diffed what I've done in develop vs master and all that seems to have changed is the checksumming. The changes to the isprop macro should be irrelevant and were just a cure for a potential crash with very short sentences. If you have two source trees there can you confirm that that's and some minor things in the makefile are all that differs for you?  I'm assuming you're using the same config file, sources etc.  Is global checksumming switched on or off?  And it isn't anything that's being caught by your ofilter that's looping back is it?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/stripydog/kplex","title":"stripydog/kplex","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/modules/aws/aws-bg.jpg","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/stripydog/kplex"}},"updates":{"snippets":[{"icon":"PERSON","message":"@stripydog in #13: I diffed what I've done in develop vs master and all that seems to have changed is the checksumming. The changes to the isprop macro should be irrelevant and were just a cure for a potential crash with very short sentences. If you have two source trees there can you confirm that that's and some minor things in the makefile are all that differs for you?  I'm assuming you're using the same config file, sources etc.  Is global checksumming switched on or off?  And it isn't anything that's being caught by your ofilter that's looping back is it?\r\n"}],"action":{"name":"View Issue","url":"https://github.com/stripydog/kplex/issues/13#issuecomment-237371463"}}}
