### ISSUE TITLE
ofilter on interface

### ISSUE THREAD

**Issue by e-sailing** [stripydog/kplex#16]
Filter on an interface doesn't work.
ofilter=-GP***%gps
Filter without an interface works.
ofilter=-GP***

`pi@openplotter:~/.config/kplex $ kplex -d 9`
`kplex DEBUG: Using config file /home/pi/.kplex.conf`
`kplex DEBUG: kplex starting, config file /home/pi/.kplex.conf`
`kplex DEBUG: opencpn: initialised`
`kplex DEBUG: gps: opened serial device /dev/ttyOP_GP for input`
`kplex DEBUG: mpx1: opened serial device /dev/ttyOP_MPX1 for input/output`
`Unknown interface '0 ▒▒7' in filter rules`
`Name to interface translation failed`
`pi@openplotter:~/.config/kplex $ kplex -V`
`1.3.3-17-g987486d`

file: .kplex.conf

[tcp]
name=opencpn
direction=out
mode=server
ofilter=-**RMB
port=10109

[serial]
name=gps
direction=in
optional=yes
filename=/dev/ttyOP_GP
baud=4800

[serial]
name=mpx1
direction=both
optional=yes
filename=/dev/ttyOP_MPX1
baud=38400
ofilter=-GP***%gps

**Comment by stripydog** [comment]
Sorry for the delay.  What platform was this on?

**Comment by e-sailing** [comment]
Latest openplotter rpi3. 
It wasn't the first time that it doesn't work. I don't know exactly if it did work at all. Should I try it with an older version?

**Comment by stripydog** [comment]
No: the problem is not showing up on x86 which is what I have available at
the moment so even if you try an earlier version on ARM and it works it
doesn't mean it's "not broken".  Thanks for finding this and apologies for
the delay in fixing: currently working a rather full-on contract away form
home.  I hope to track this down this week, if not I'll have access to a pi
on the weekend

**Comment by stripydog** [comment]
I've found *a* problem with interface name initialisation which has been fixed in the develop branch.  Can you give it a try?  Hopefully it's your problem. Trailing null wasn't being added to interface names and on x86 the storage malloc-ed for them happened to be full of nulls...

**Comment by e-sailing** [comment]
I compiled the latest develop branch.
Same as before. If I change the sequence of the three blocks, I directly get a Segmentation fault.

pi@openplotter:~ $ kplex -d 9
kplex DEBUG: Using config file /home/pi/.kplex.conf
kplex DEBUG: kplex starting, config file /home/pi/.kplex.conf
kplex DEBUG: mpx1: opened serial device /dev/ttyOP_MPX1 for input/output
kplex DEBUG: opencpn: initialised
kplex DEBUG: gps1: opened serial device /dev/ttyOP_GP for input/output
Segmentation fault
pi@openplotter:~ $ kplex -d 9
kplex DEBUG: Using config file /home/pi/.kplex.conf
kplex DEBUG: kplex starting, config file /home/pi/.kplex.conf
kplex DEBUG: opencpn: initialised
kplex DEBUG: gps1: opened serial device /dev/ttyOP_GP for input/output
kplex DEBUG: mpx1: opened serial device /dev/ttyOP_MPX1 for input/output
Unknown interface '
                   ▒▒0▒0
                        ▒' in filter rules
Name to interface translation failed
pi@openplotter:~ $

When I delete the first block (opencpn). I get this error:

pi@openplotter:~ $ kplex -d 9
kplex DEBUG: Using config file /home/pi/.kplex.conf
kplex DEBUG: kplex starting, config file /home/pi/.kplex.conf
kplex DEBUG: gps: opened serial device /dev/ttyOP_GP for input/output
kplex DEBUG: mpx1: opened serial device /dev/ttyOP_MPX1 for input/output
Unknown interface ELF' in filter rules
Name to interface translation failed
pi@openplotter:~ $

**Comment by stripydog** [comment]
Thanks again.  Did you change the gps interface to be input/output or is that a clue?

What would be really helpful would be if you could get a core dump then do a stack trace and send me that. Core dump no good for me until I've got a pi which I can hopefully pick up on the weekend.

btw I've rebased the develop branch to get rid of a big chunk of code I wasn't happy with but that would have been unlikely to be where your problem lay. You might want to re-pull and recompile anyway.

Thanks for your patience

**Comment by stripydog** [comment]
Sorry it's been so long: I've been bound up with a job and didn't fire up a pi for months.  Tonight I did with a couple of serial interfaces and reproduced and, hopefully, fixed what you were seeing.  The problem was that in looping through interfaces to resolve the interface names on filters and convert them to ids both the input and output sides were trying to manipulate the output filter resulting in a double free.  SHould be fixed in the develop branch.  Once again apologies for the long delay

**Comment by e-sailing** [comment]
Thanks! Now it works!
