### ISSUE TITLE
Missing GitHub Release tag for v1.3.4

### ISSUE THREAD

**Issue by caesar** [stripydog/kplex#17]
I'm just creating a [Homebrew](https://brew.sh/) formula for kplex, which requires a link to download a source tarball for the current version – but I see that the latest version, 1.3.4, is missing from the GitHub Releases page and is not tagged in Git.

At present I'm using the source tarball hosted on your website in the formula, but ideally I think a GitHub link would be better due to the ability to use their CDN (and HTTPS).

**Comment by stripydog** [comment]
Thanks for spotting.  Hopefully should be fixed: I just built from github clone and download on OS X.  Appreciate it if you could check it

**Comment by caesar** [comment]
I see the new tag (and GitHub releases entry), great, thanks.

I was already running v1.3.4 built from a checkout of `master` so all is good there. :-)
