### ISSUE TITLE
Config filename/location

### ISSUE THREAD

**Issue by caesar** [stripydog/kplex#18]
I'm pleased to see the ability to store per-user config in the `~/Preferences` directory for macOS users. Would you consider adding support for `$XDG_CONFIG_HOME` for Linux (and other systems), rather than storing the config file directly in the home directory?

Also – this isn't a major issue, but I'm puzzled by the choice of filename for the per-user config on macOS. Like on other Unixes, `.conf` is a much more common file extension for configuration files than `.ini` – the latter is, I believe, more common on Windows.
Perhaps it's not worth changing it now, but I'm curious as to why you chose to use `.ini` for the per-user config file on macOS when you use `.conf` for the same file on other systems (and for the global config on macOS, too).

**Comment by caesar** [comment]
@stripydog, you mentioned in personal communication that kplex will use a custom config location set in a `KPLEXCONF` environment variable. This is good to know.

I just wanted to clarify a couple of thoughts and I thought I'd do it here rather than by email.

First, of course, the point of the XDG basedir spec is to be a standard for all installed software, so that one doesn't have to set custom env vars for each program (though the custom variable, if set, would obviously override XDG).

Second, I guess when I suggest adding XDG support I'm thinking not just of using the `$XDG_*` vars if they exist, but also of honouring the defaults from the XDG standard if they don't.

So the config-file resolution algorithm would probably check the following in order when looking for per-user config, and use the first one that exists:

1. `$KPLEXCONF`
2. `$XDG_CONFIG_HOME/kplex/kplex.conf` (if `$XDG_CONFIG_HOME` is set)
3. `$HOME/.config/kplex/kplex.conf` (if `$XDG_CONFIG_HOME` is *not* set)
4. `~/Library/Preferences/kplex.conf` (on macOS)
5. `~/Library/Preferences/kplex.ini` (on macOS) for back compat
6. `~/.kplex.conf` for back compat

A future semver-major release could drop 5 and 6 maybe?

(Incidentally, I am not fully sure that `~/Library/Preferences/` is even the right place to store this file on macOS. It seems to be mostly used by the macOS preferences system for storing window position etc, in plist files. (Also, files here are named using reverse DNS syntax, so com.stripydog.kplex.conf would be the right name I suppose.) Most other software seems to use a subdirectory of `~/Library/Application Support/`. I'm not sure about this, so would look for a guideline from Apple before thinking about changing it.)

**Comment by stripydog** [comment]
2 issues here.  Firstly XDG Base Directory.  I appreciate the concept but not sure it's right here.  Free desktop.org do standards for desktops.  kplex isn't really a desktop app so you wouldn't necessarily expect to find its configuration file with those for your gnome or kde apps.  If we're following the standard we'd also have to be honouring XDG_CONFIG_DIRS and if that's not set looking in /etc/xdg/kplex/kplex.conf.  I don't think that's a good place for the config file.  I'll keep this issue open for now but my feeling towards it isn't especially enthusiastic. This won't go into the upcoming (minor) release.

On the OS X front...I really don't know about the naming.  I put it in there before I owned a mac and am guessing I took a look at a friend's mac and cribbed the naming from there.  Looking on the mac I now own there doesn't seem to be any reason to favour ".ini" over ".conf".  I'm not a huge fan of using a domain name as any kind of significance to an application though.  Need to think about this one a bit...

As for Application Support vs. Preferences after a bit of research I'm leaning towards thinking that Preferences is the right place for configuration with Application Support being more for stuff like plugins but happy to be convinced on that.

I'm sympathetic to changing the conf file to .conf on Mac (whilst retaining backwards .ini support).  I understand the reverse dns argument but haven't drunk the java cool aid so don't much care for it. I see the argument for a subduer but it seems a bit of a redundant step for a user to have to create a separate directory for a single file.  what are your thoughts?

**Comment by caesar** [comment]
I agree with much of what you say about XDG – yes, the standard was originally for desktop apps, and yes, `/etc/xdg/kplex/kplex.conf` would IMO be the wrong place for kplex's global config. So I guess I don't think you should fully follow the spec despite what I originally said.

That said, the use of the `.config` dir to store config is not exclusive to GUI apps (or to Linux) even if that was the original intent. It is often used by CLI apps – two examples off the top of my head are git and neovim. And it helps to declutter the home directory and keep all per-user config together. I've always hated having my home dir cluttered with config files.

I'll follow up with my thought on the macOS issues in a second message...

**Comment by caesar** [comment]
Ok, macOS. I'd be in favour of switching to `.conf` (with backwards compat until the next major release).

I am also leaning towards `Preferences`. Several apps on my system are using `Application Support` for preferences, but in my opinion it's wrong. None of Apple's apps seem to do this.

That said, your XDG-is-for-GUI-apps argument sort of applies here too. Pretty much all the apps which use the `~/Library/` subdirs are GUI apps, while CLI apps (especially cross-platform ones) seem to put config in the home dir or in `~/.config` just as on Linux.
Not saying you should follow this trend, I don't know what is 'right', it's just an observation.

As for reverse DNS syntax for naming, I've always found it ugly, but it does serve a purpose in that it ensures no naming collisions.
I'd note though that all the reverse-DNS-named files in `~/Library/Preferences` are plists, so for a different type of file maybe there's no special reason to fit in with that naming scheme. I'd stick with `kplex.conf` myself.

**Comment by stripydog** [comment]
~/.kplex.conf is now supported and preferred on OSX.  The ini file will still be used in preference for backwards compatibility (I'm not making changes which might break something except in a major release) but a warning message about its deprecation is now logged.  I'll make any other changes in 2.0

**Comment by caesar** [comment]
Sorry, I thought I'd replied to this at the time of your comment, but evidently I didn't…

Much as I'm happy to see the `.ini` changed to `.conf`, I have to admit I'm less thrilled about the move into the home dir. I hate clutter in my home dir…
I know you've said you don't want to use XDG's `~/.config/kplex/` (and I'm kind of giving up advocating for XDG in general, as it seems to be a losing battle in most cases) but I thought the previous `~/Library/Preferences/` was a fine way to avoid clutter in `~/`.

But maybe you just want to use a consistent location across platforms, which I can totally understand (even though in that case I'd still 'vote' for `~/config/kplex/`).

TBH I don't use per-user config myself anyway so this is all theoretical for me! 😄

**Comment by stripydog** [comment]
Meeting you half way: ~/Library/Preferences/kplex.conf added in as optional config location for OSX in 1.4rc2
