### ISSUE TITLE
Man page

### ISSUE THREAD

**Issue by caesar** [stripydog/kplex#19]
Have you considered adding a man page for kplex? This would be really useful I think as those who had installed from a package manager rather than from source would then still have offline access to the documentation.
Perhaps the man page and the readme could both be auto-generated from the same source.

(Sorry for the spate of new issues all together…)

**Comment by stripydog** [comment]
Need for man page has been recognised for years but the the documentation is now too big to be conveniently nroffed.  What can be done without too much work is to go with the gnu model of listing the summary info in the man page with a link to the online documentation and the README  which would be installed under /usr/share/doc.  Would this work?

**Comment by caesar** [comment]
Hmm... it's true the kplex documetnation is long. But I don't know if it's *too* long for a manpage. Some manpages are huge! If there's a way to get all/most of the documentation into the man page itself I feel that would be preferable, but your suggestion of only including the basics and then linking to detailed documentation elsewhere would work too I suppose.

A few thoughts:

* I have seen projects which generate both the readme and the man page from a single markdown or asciidoc source. I confess I have little experience with the arcane manpage syntax, but I could check this idea out. In particular, see http://www.eddieantonio.ca/blog/2015/12/18/authoring-manpages-in-markdown-with-pandoc/ (Pandoc is an absolutely amazing tool) or alternatively dedicated tools like https://github.com/rtomayko/ronn. I think it would be easy to reformat the readme to work with these tools.

* Against the above technique: it would be better not to introduce build-time dependencies for users just for the sake of 'building' the manpage. If you followed that route, maybe better if the manpage building was a totally separate task and the built manpage was committed to git? Though committing built files goes against the grain...

* Do the readme and the manpage even both need/want to contain the same info? Obviously the build/install instructions don't belong in the manpage, perhaps nor do the Q&A or the To Do sections. And maybe the full documentation of all the options doesn't really belong in the readme?

* Maybe all the information doesn't belong on one man page anyway. Perhaps the general options should be in `kplex(1)` and the config syntax in `kplex.conf(5)` or `kplex.conf(7)`.

What do you think? Anyway obviously none of this is a pressing issue, just something to think about at some point.

**Comment by stripydog** [comment]
I've been about to release a minor update for weeks now with some niggling problem in my deb creation workflow plus no free time holding me up so I'm not going to do anything major in the immediate future. However the lack of man page has been niggling me for years so I will put the stub in referencing the rest of the docs.  I'll check out the links you've given too but for now I'll just use old fashioned nroff.  Not all the README is man page material but more of it is than isn't so I think it's valid to reference it in the stub man page:  I noticed the gnu cpio man page does something similar and the bulkier gnu stuff have been referencing the info docs for years.  Yes breaking out into kplex and kplex,conf makes sense but I might leave that for the next big release

**Comment by caesar** [comment]
Sounds good, just getting something out will be a start and like you say you can always add to it in a later release.

**Comment by pvint** [comment]
+1 on the man page, even if it's minimal.

I just downloaded from git, compiled, and the first thing I did was `./kplex --help` which didn't work, so I did `man kplex`, which also didn't work. ;) 

Over the next month or so I expect to really start experimenting with this for my projects, and once I have gotten to know it better maybe I can throw together a man page for you.

**Comment by stripydog** [comment]
The man page is in the develop branch.  I'm not a github expert but isn't it bundled up from master?  You'll see the man page in the develop branch and in the tar file on my web site.

**Comment by stripydog** [comment]
Man page now in 1.4.  closing this now but not precluding a move to a more comprehensive man page

**Comment by caesar** [comment]
Great stuff Keith!
Of course a more comprehensive man page would be even better, but this is a great start. Thanks!
