### ISSUE TITLE
Version only works with git

### ISSUE THREAD

**Issue by nunojpg** [stripydog/kplex#2]
If I just download a TAR of the repository and build kplex, then kplex -V will have a empty string.

That is because the entire version string depends on git. I believe the header file shall have the base version (v1.3), and git shall only be used to append to ip.

**Comment by stripydog** [comment]
There's a fix for this in the develop branch: checked in a few months ago.   To be honest I'm still getting the hang of this github malarkey: kplex has only been on here a few months....
