### ISSUE TITLE
Kplex fails DNS-lookup at boot and never retries

### ISSUE THREAD

**Issue by marcus-aa** [stripydog/kplex#22]
Outgoing TCP connections using DNS names fail (probably due to kplex starting before DNS is available). Connections using IP address works normally.
Kplex seems to never retry after first attempt.

kplex[410]: Lookup failed for host ais1.server.net/service 6543: Name or service not known 
kplex[410]: Failed to initialize Interface _tcp-id4

Stopping and starting kplex manually after boot solves the issue.

Config used:

[serial]
filename=/dev/ttyUSB0
direction=in
baud=38400
optional=no

[tcp]
mode=server
port=10110
direction=out
optional=yes

[tcp]
mode=client
optional=yes
address=ais1.server.net
port=6543
persist=fromstart
retry=15
timeout=30
direction=out
keepalive=no

**Comment by stripydog** [comment]
This looks like an issue with boot order dependencies.  What OS, systemd or init if Linux, and what does your init script / unit file look like?

**Comment by marcus-aa** [comment]
Debian Jessie/Stretch on Raspberry ARM, insatlled with 
update-rc.d kplex defaults 
using original /etc/init.d/kplex

**Comment by marcus-aa** [comment]
#!/bin/sh

### BEGIN INIT INFO
# Provides:        nmeamultiplex
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Start kplex NMEA 0183 multiplexer
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

DAEMON=/usr/bin/kplex
KPLEXCONF=/etc/kplex.conf
RUN_AS_USER=root

test -x $DAEMON || exit 5
test -r $KPLEXCONF || exit 5

case $1 in
	start)
		log_daemon_msg "Starting kplex multiplexer" "kplex"
  		start-stop-daemon --start --quiet --oknodo --exec $DAEMON --startas $DAEMON --chuid $RUN_AS_USER -- -f $KPLEXCONF -o mode=background
		status=$?
		log_end_msg $status
  		;;
	stop)
		log_daemon_msg "Stopping kplex multiplexer" "kplex"
  		start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
		log_end_msg $?
  		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;
	try-restart)
		if $0 status >/dev/null; then
			$0 restart
		else
			exit 0
		fi
		;;
	reload)
		exit 3
		;;
	status)
		status_of_proc $DAEMON "kplex NMEA 0183 multiplexer"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac

**Comment by marcus-aa** [comment]
Any change on this in last version?

**Comment by stripydog** [comment]
Apologies for the super-long time taken to reply.  There's been various reports of legacy init scripts not being invoked in the correct order.  A reinstall seems to fix it but no-one wants to do that.  As of the next release I'm going to move to using a systemd unit file but there was one included in the 1.4 release which should work OK.  Do you want to try ditching the init files and going with the kit file?  It's provided with the deb in /usr/share/kplex/kplex.service

**Comment by stripydog** [comment]
Actually turns out the unit file in the deb package has a typo which is now corrected in the master and develop branches on GitHub

**Comment by stripydog** [comment]
Hopefully the new unit file fixes this.  This will be the default in the next release.  Also, adding persist=fromstart should re-try lookups for tcp connections, though not udp.  If there's anything else to be done on this issue let me know, otherwise I'll close it in 5 days

**Comment by marcus-aa** [comment]
Sorry for the late answer, I'm on vacation out on the boat and don't have access to my test systems. Will try to check remotely but it sounds promising.
