### ISSUE TITLE
Kplex does not re-query DNS after TTL expiry, even if old IP stops responding. 

### ISSUE THREAD

**Issue by marcus-aa** [stripydog/kplex#23]
When a DNS name changes IP address on the name servers, kplex continues to keep an ongoing TCP connection seemingly forever (tested 2 months after ttl). But even if the old endpoint stops responding, kplex keeps trying to re-connect to the old IP address. 

A ping to the server name on the same machine resolves correctly, so the DNS updates are working.

**Comment by stripydog** [comment]
Correct me if I'm wrong but I'm assuming you have a client tcp connection to a server with a dynamic (or changed) IP address.  kplex resolves its endpoint once, when the interface is initialised and in "persist" mode will carry on trying to reconnect to the same address.

Obviously kplex knows nothing of dns: it just uses the system resolver so will be unaware of TTLs.  This certainly isn't a bug but if I understand your use case correctly it's a feature request for an option to re-resolve the server name upon reconnection.  Would that be correct?

If so I'll check what's involved...

**Comment by marcus-aa** [comment]
Maybe not a bug, but definitely an "issue" :-) 

If DNS names are allowed instead of ip addresses, they should be re-resolved at some point, that is the whole idea of DNS names, that the underlying IP can change any time.

I understand that kplex doesn't know about ttl, but the normal way would seem to be to re-query the DNS resolver every time kplex re-connects to an endpoint, as the failure to connect may very well be caused by a changed IP address for the hostname. The DNS resolver keeps track of ttl issues and can provide a cached address so there should only be a minor load on the external dns service.

It would solve a lot of problems if this behavior could be changed. Or added as a feature !

**Comment by stripydog** [comment]
ack.  will re-visit

**Comment by stripydog** [comment]
I really haven't done much on kplex for over a year but am now working my way through outstanding issues.  Sorry for the delay.  I agree this is the right thing to do and am looking at implementing it for the next release

**Comment by stripydog** [comment]
The relookup branch should re-resolve hostnames for lost connections when it tries to reconnect.   If you get a chance to give it a try, let me know if it does what you expect

**Comment by stripydog** [comment]
Did you get a chance to try the relookup branch?  If you could confirm it does what you want that would be wonderful.  Thanks

**Comment by marcus-aa** [comment]
Sorry for the late answer, I'm on vacation out on the boat and don't have access to my test systems. Will try to check remotely but it sounds just right.

**Comment by stripydog** [comment]
Do let me know if that branch works as required and I'll merge it into develop

**Comment by stripydog** [comment]
I'll merge this into develop and close the issue if I hear nothing in the next 4 days

**Comment by stripydog** [comment]
Nothing heard.  Merged and closing.
