### ISSUE TITLE
[Feature] Rewrite sentence from one Talker ID to another Talker ID

### ISSUE THREAD

**Issue by bwssytems** [stripydog/kplex#24]
I have a Sitex Autopilot SP110 and it outputs heading data as "$APHDM". It seems a lot of nmea systems prefer "$HCHDM" and I would like a filter with replace option to convert $AP with $HC.

Let me know what you think.

Thanks for this great piece of software!

**Comment by bwssytems** [comment]
For now, I have created a converter that rewrites $AP to $HC talkers that serves on port 6789. Configure kplex to have tcp client that goes to that port and and filter for your messages and define both directions and it will loop it out and back.

https://github.com/bwssytems/MarineNMEATools

**Comment by stripydog** [comment]
SO sorry I never replied to this.  Just going through old issues.  Humblest apologies.  A generic filter mechanism where you could plugin any kind of converter script was always planned but never implemented and having done some work on kplex for the first time in ages recently I realise it's waaaay over-complex and due a ground-up rewrite so new features are going to be minimal for the foreseeable future.  Hope the solution you have here is working for you.  As you may have realised you can ensure the unwanted talker ID doesn't get seen anywhere except your converter using filters.  So the output to your converter program would have ofilter=+APHDM:-all and all other outputs except the autopilot would have ofilter=-APHDM (or you could do it by including/excluding sentences from the autopilot interface).  Conversion of talkers would not be a huge task but the generic conversion is the goal an that won't be in the foreseeable future.

**Comment by bwssytems** [comment]
No problem and thanks for the reply. My converter does just fine so I am good. This is still the core piece of software on my boat and appreciate the work that goes into it.

**Comment by stripydog** [comment]
Thanks for the feedback.  I'll close this issue for now if you don't mind
