### ISSUE TITLE
TCP preamble parsing error

### ISSUE THREAD

**Issue by jotx** [stripydog/kplex#25]
There is an error in the [parse_preamble](https://github.com/stripydog/kplex/blob/master/tcp.c#L727) function for hex values.
```C
                    if (*optr >= '0' && *optr <= '9')
                        tval += *ptr - '0';    // should probably be *optr
```
I also tried using the octal option but could not get to work either. No clue what the problem is there however.
The preamble I used:
`preamble=\x01username\x00password\x00`

**Comment by stripydog** [comment]
Yikes you're right! well spotted (and sorry...). I'll fix this in the next few days and get it into the 1.4 release

**Comment by stripydog** [comment]
You're right: Don't know what's happened there.  committed the change, pushed the branch and went to bed. branch there but change not.  I'll check my computer when I get back from work this evening

**Comment by stripydog** [comment]
Bit of a late-night error there. sorry.  Should be ok now. give it a try

**Comment by jotx** [comment]
Working fine for me! Tried both hex and octal.

**Comment by stripydog** [comment]
Fabulous.  I leave this open a couple of days then close if you don't see further problems.

Many thanks again for highlighting this
