### ISSUE TITLE
Documentation addition.

### ISSUE THREAD

**Issue by FredericGuilbault** [stripydog/kplex#33]
Hi, I have found out that it's possible to run the kplex armhf package on an arm64 arch (with the armbian OS). 

The only tweak it need is forcing the arch on depending packages like this :
`apt-get install gcc-8-base:armhf libc6:armhf libgcc1:armhf`
Before installing the package otherwise it complain about missing deps. 

_For ref, my full install procedure is here : https://github.com/lysmarine/lysmarine_gen/tree/master/lysmarine/31-kplex_ 

Having arm64 package would be the best but meanwhile, I think this might worth being documented somewhere.

**Comment by stripydog** [comment]
Thanks and sorry for the incredibly long time to reply.  I'm going to try and acquire a pi 4 to play with but I'll look at putting a note in the documentation in the next week.  DO you mind if I link to your instructions?

**Comment by FredericGuilbault** [comment]
Sure, no Problems.

I tested it on a PineA64 and qemu. not a Rpi4, But it should be the same.

**Comment by stripydog** [comment]
Thanks again Frederic.  I've updated the install page here:
http://www.stripydog.com/kplex/kplex.html

..and put a note in the "news" section on the kplex main page.

I'll re-write this when I get hold of a new pi and play with 64-bit raspbian and will ensure I build an arm64 package for the next release.

Keith
