### ISSUE TITLE
kplex accepts input it can't filter

### ISSUE THREAD

**Issue by stripydog** [stripydog/kplex#39]
Raised in: [](https://github.com/SignalK/signalk-server/issues/1111)

Sentences with fewer than 6 characters excluding trailers may be accepted into kplex but then there is no way to filter them, leading to the possibility of data loops.  In the above scenario a short sentence !A is being accepted but then cannot be filtered.

Sentences should be checked for minimum length in talker id /formatter, although an open question arises of whether a proprietary sentence with nothing after the manufacturer id is valid

**Comment by stripydog** [comment]
Fix in the "shorts" branch:

- ensures at least 5 characters other than start char, checksum and \r\n
- ensures no misplaced '*' characters which may have been allowed if checksumming switched off

This will exclude proprietary sentences which contain no data, e.g.:
$PXYZ
Is that a problem?  Is that allowed by the spec?  I can't see that such sentences would be of any use.  If anyone reports this as an issue I'll fix that too but for now it seems acceptable.

**Comment by ghost** [comment]
I have it built and am testing now. I will let you know in the next day or two if I see this issue again. So far all looks to be well.

**Comment by ghost** [comment]
It has been several days and all seems well. I would call this closed.

Thank you for your help!

**Comment by stripydog** [comment]
Thanks for checking it out.  I'll merge this.  Not sure how long before
this makes it to production: there's quite a big change I have in the
pipeline for 1.5 which enables people to loop in their own filter scripts
into the input/output of kplex which will need a fairly long beta test, but
1.5 sometime in the next few months for sure.

Thanks again

Keith

**Comment by stripydog** [comment]
merged and closing
