### ISSUE TITLE
documentation correction

### ISSUE THREAD

**Issue by sailoog** [stripydog/kplex#4]
I can't find the useful optional=yes/no option on http://www.stripydog.com/kplex/configuration.html
but it is on github readme and working on 1.3 release.
Thanks for this great software.

**Comment by stripydog** [comment]
Good spot: Many thanks. I update the web page manually from changes to the
README every time I do a release.  This was a (bad) mistake.  Now corrected.

Thanks again

Keith


I can't find the useful optional=yes/no option on
> http://www.stripydog.com/kplex/configuration.html
> but it is on github readme and working on 1.3 release.
>

**Comment by sailoog** [comment]
you are welcome :)
