### ISSUE TITLE
kernel module option not works with latest kplex

### ISSUE THREAD

**Issue by zokl** [stripydog/kplex#56]
Hello, I would like to use kplex for multiplexing GPS receiver of my modem which uses `option` module. I have following error:

```
root@FTWireless-5817D4:~# kplex -d 9 -f- serial:filename=/dev/ttyUSB1 file:filename=/dev/gps,direction=out
kplex DEBUG: kplex starting, config file <none>
kplex DEBUG: _serial-id1: opened serial device /dev/ttyUSB1 for input/output
Failed to correctly set up serial line
Failed to initialize Interface _serial-id1
```

```
root@FTWireless-5817D4:~# kplex -V
1.4
```

```
root@FTWireless-5817D4:~# cat /dev/ttyUSB1
$GPGSA,A,3,04,07,09,16,30,,,,,,,,2.8,2.1,1.9,1*20
$GPVTG,,T,,M,0.0,N,0.0,K,A*23
$GPRMC,075206.00,A,5006.159704,N,01423.597644,E,0.0,,040122,1.3,E,A,V*64
$GPGGA,075206.00,5006.159704,N,01423.597644,E,1,05,2.1,247.3,M,45.0,M,,*6B
$GPGSA,A,3,04,07,09,16,30,,,,,,,,2.8,2.1,1.9,1*20
$GPVTG,,T,,M,0.0,N,0.0,K,A*23
$GPRMC,075207.00,A,5006.159704,N,01423.597645,E,0.0,,040122,1.3,E,A,V*64
$GPGGA,075207.00,5006.159704,N,01423.597645,E,1,05,2.1,247.3,M,45.0,M,,*6B
$GPGSA,A,3,04,07,09,16,30,,,,,,,,2.8,2.1,1.9,1*20
$GPVTG,,T,,M,0.0,N,0.0,K,A*23
$GPRMC,075209.00,A,5006.159703,N,01423.597650,E,0.0,,040122,1.3,E,A,V*69
$GPGGA,075209.00,5006.159703,N,01423.597650,E,1,05,2.1,247.3,M,45.0,M,,*66
```

**Comment by stripydog** [comment]
I'm totally unfamiliar with the "option" module but a quick google suggests that the baud rate may not be settable.  kplex will default to the NMEA standard of 4800 baud.  If it can't set the baud rate the interface will fail.  My first suggestion would be to simply use the standard usb serial driver.  Second would be to see what baud rate it's already using (stty < /dev/ttyUSB1) and tell kplex to use that.  It might still fail, in which case try opening it as a "file" interface with direction=in.

**Comment by zokl** [comment]
> I'm totally unfamiliar with the "option" module but a quick google suggests that the baud rate may not be settable. kplex will default to the NMEA standard of 4800 baud. If it can't set the baud rate the interface will fail. My first suggestion would be to simply use the standard usb serial driver. Second would be to see what baud rate it's already using (stty < /dev/ttyUSB1) and tell kplex to use that. It might still fail, in which case try opening it as a "file" interface with direction=in.

Thank you very much. Baud rate change according to option module speed works. The default speed is 9600 Bps.
