### ISSUE TITLE
Include debian packaging in github

### ISSUE THREAD

**Issue by bakerkj** [stripydog/kplex#9]
Hi Keith,

Any chance you could also add the debian directory used to create your debs in the github repo?

Thanks!

-- Ken

**Comment by stripydog** [comment]
I'll regretfully say sorry no for now.  I'm pretty sure it's not the ideal way to do it (I"m way better with rpm, but no-one seems to use rpm for kplex) and every time I change the makefile I have to re-read about how to do it.  So I'm saying that for now anyone can do this better than me but I'll reconsider this if I get my toolchain cleaner.
